# Generated by Django 6.0 on 2025-12-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
